version: '3.8'

# Override file for development
services:
  app:
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        npm install &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run dev
      "
    
  database:
    ports:
      - "5432:5432"  # Expose database port for development